# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1468299585);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1468299710323");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1468301446323");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1468299591950");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1468303191950");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160630070928");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1468299649");
user_pref("browser.slowStartup.averageTime", 15537);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20160630070928");
user_pref("browser.startup.homepage_override.mstone", "47.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":2}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"pocket-button\",\"loop-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"downloads-button\",\"ublock0-button\",\"flashstopper-toolbarbutton\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"loop-button\",\"pocket-button\",\"ublock0-button\",\"flashstopper-toolbarbutton\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1468299659128");
user_pref("datareporting.sessions.current.activeTicks", 13);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3610);
user_pref("datareporting.sessions.current.main", 1810);
user_pref("datareporting.sessions.current.sessionRestored", 3792);
user_pref("datareporting.sessions.current.startTime", "1468299645340");
user_pref("datareporting.sessions.current.totalTime", 66);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1468299559424,\"a\":10,\"t\":77,\"c\":true,\"m\":23670,\"fp\":27034,\"sr\":27391}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "unsupportedChannel");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"uBlock0@raymondhill.net\":{\"version\":\"1.7.6\",\"type\":\"extension\",\"descriptor\":\"/home/gtespe/.mozilla/firefox/366j48ag.selenium/extensions/uBlock0@raymondhill.net.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false},\"firefox@getpocket.com\":{\"version\":\"1.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"loop@mozilla.org\":{\"version\":\"1.3.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"flashstopper@byo.co.il\":{\"version\":\"1.4.2\",\"type\":\"extension\",\"descriptor\":\"/home/gtespe/.mozilla/firefox/366j48ag.selenium/extensions/flashstopper@byo.co.il.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7B8935f540-b136-11e0-a00b-0800200c9a66%7D:1.5.1.1-signed.1-signed,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:47.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "47.0.1");
user_pref("extensions.lastPlatformVersion", "47.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.xpiState", "{\"app-profile\":{\"uBlock0@raymondhill.net\":{\"d\":\"/home/gtespe/.mozilla/firefox/366j48ag.selenium/extensions/uBlock0@raymondhill.net.xpi\",\"e\":true,\"v\":\"1.7.6\",\"st\":1468299622000},\"{8935f540-b136-11e0-a00b-0800200c9a66}\":{\"d\":\"/home/gtespe/.mozilla/firefox/366j48ag.selenium/extensions/{8935f540-b136-11e0-a00b-0800200c9a66}.xpi\",\"e\":true,\"v\":\"1.5.1.1-signed.1-signed\",\"st\":1468299647000},\"flashstopper@byo.co.il\":{\"d\":\"/home/gtespe/.mozilla/firefox/366j48ag.selenium/extensions/flashstopper@byo.co.il.xpi\",\"e\":true,\"v\":\"1.4.2\",\"st\":1468299701000}},\"app-system-defaults\":{\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.2\",\"st\":1467272193000},\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3.2\",\"st\":1467272193000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1467272193000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"47.0.1\",\"st\":1467272193000}}}");
user_pref("gecko.buildID", "20160630070928");
user_pref("gecko.mstone", "47.0.1");
user_pref("loop.copy.ticket", 21);
user_pref("media.gmp-manager.buildID", "20160630070928");
user_pref("media.gmp-manager.lastCheck", 1468299709);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1468299647);
user_pref("toolkit.telemetry.cachedClientID", "91ffd3b4-48dd-4589-8f32-f8f1c9486817");
user_pref("toolkit.telemetry.previousBuildID", "20160630070928");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
